//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TouchScreenExample
{
    
    internal partial class Resources
    {
        private static System.Resources.ResourceManager manager;
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((Resources.manager == null))
                {
                    Resources.manager = new System.Resources.ResourceManager("TouchScreenExample.Resources", typeof(Resources).Assembly);
                }
                return Resources.manager;
            }
        }
        internal static Microsoft.SPOT.Font GetFont(Resources.FontResources id)
        {
            return ((Microsoft.SPOT.Font)(Microsoft.SPOT.ResourceUtility.GetObject(ResourceManager, id)));
        }
        internal static string GetString(Resources.StringResources id)
        {
            return ((string)(Microsoft.SPOT.ResourceUtility.GetObject(ResourceManager, id)));
        }
        internal static byte[] GetBytes(Resources.BinaryResources id)
        {
            return ((byte[])(Microsoft.SPOT.ResourceUtility.GetObject(ResourceManager, id)));
        }
        [System.SerializableAttribute()]
        internal enum FontResources : short
        {
            Calibri8 = -29509,
            Calibri8AA = -24993,
            Calibri20AA = -16725,
            Calibri26 = -16282,
            Calibri20 = -16276,
            Calibri12Bold = -14290,
            Calibri16Bold = -10198,
            Calibri16 = -4565,
            Calibri12 = -4561,
            Calibri32Bold = 4586,
            Calibri32 = 4618,
            Calibri8Bold = 7284,
            Calibri20Bold = 9830,
            Calibri26Bold = 11748,
            small = 13070,
            med = 15380,
            big = 21410,
            Calibri16AA = 25315,
            Calibri12AA = 27935,
        }
        [System.SerializableAttribute()]
        internal enum BinaryResources : short
        {
            Clibold = -27322,
            icon_left = 13674,
        }
        [System.SerializableAttribute()]
        internal enum StringResources : short
        {
            String1 = 1228,
        }
    }
}
